//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by tabdoc.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define CG_ID_VIEW_WORKSPACE            103
#define IDD_ADDFORM                     105
#define IDD_LOOKFORM                    106
#define IDD_PROPPAGE_NEWDOWND           106
#define IDS_LOAD_FAILURED               107
#define IDR_HTML_MRUTASKDLG             111
#define ID_APP_HELP                     117
#define CG_ID_VIEW_ANCHORS              118
#define IDM_CUT                         119
#define IDM_CUT_ALL                     120
#define IDM_COPY_ALL_URLS               121
#define IDM_COPY_SRC_URLS               122
#define IDM_COPY_REF_URLS               123
#define IDM_COPY_NO_URLS                124
#define IDM_ELEMENT_PROPERTY            125
#define IDC_BUTTON_RESUME               126
#define ID_CATCH_TOOL                   127
#define IDR_MAINFRAME                   128
#define IDR_tabdocTYPE                  129
#define IDS_E_CREATE_DIRECTORY1         130
#define IDS_URL_OPEN_FAILURE            131
#define IDS_INET_INIT_FAILURE           132
#define IDS_BUFF_FILE_FAILURE           133
#define IDR_FAVORITES_POPUP             133
#define IDS_ANCHOR_ZERO                 134
#define IDS_CHECKED_ALL                 134
#define IDS_ANCHOR_COUNT                135
#define IDS_E_NO_ANCHOR                 136
#define IDS_E_SELECT_DIRECTORY          137
#define IDS_E_URL                       138
#define IDS_E_JOB_EXIT                  139
#define IDS_E_JOB_EXIST                 139
#define IDS_MAX_SIZE                    140
#define IDS_MAX_FILESIZE                141
#define IDD_DLG_WAITING                 142
#define IDS_RETRY_TIMES                 142
#define IDS_AUTO_MODE_USE               142
#define IDS_CUT_ALL_CHECKED             143
#define IDD_NEWTASK_AUTO                144
#define IDS_LIMIT_ERROR                 144
#define IDD_OPTION_SYS                  145
#define IDS_RESET_ALL_CHECKED           145
#define IDS_HOMEPAGE                    146
#define IDD_RECENTTASK                  147
#define IDS_SUPPORT_SHOW                147
#define IDS_QUITWARN                    148
#define IDS_SUPPORT_MAIL                149
#define IDS_COLLECTION_MODE             150
#define IDD_OPTION_DOWNLOAD             151
#define IDS_AUTO_MODE                   151
#define IDD_OPTION_PROXY                152
#define IDS_ENTER_VALID_FILE_NAME       152
#define IDD_OPTION_FILETYPE             153
#define IDS_QUERY                       153
#define IDS_QUERY_DOWNLOD               153
#define IDS_ELEMENT_CAP                 154
#define IDS_MAXWAITTIME                 157
#define IDS_CONNECTTRY                  158
#define IDS_TRDNUMBER                   159
#define IDD_CONNECTTESTDLG              161
#define IDD_DIALOG_PAD                  164
#define IDS_WAITFORSHUTDOWN             164
#define IDB_PAUSE                       169
#define IDB_START                       170
#define IDB_STOP                        171
#define IDB_PAUSEDOWN                   172
#define IDB_STARTDOWN                   173
#define IDB_STOPDOWN                    174
#define IDB_TASK_LIST_IMAGE             175
#define IDB_HOT_BAR                     176
#define IDB_SPLASH                      177
#define IDB_COLD_BAR                    178
#define IDD_URL_EDIT_DLG                179
#define IDR_TASK_POPMENU                179
#define IDI_ICON1                       186
#define IDD_OPTION_MODIFY               187
#define IDC_HAND_POINT                  188
#define IDD_DLG_WORKMODE                190
#define IDD_NEWTASK_ANCHOR              191
#define IDC_SESSIONTREE                 192
#define IDD_PROPPAGE_FINISH             192
#define ID_START_TASK                   193
#define IDB_LOGO                        193
#define ID_STOP_TASK                    194
#define ID_KILL_TASK                    195
#define IDD_DIALOG_PLAYER               195
#define IDC_GRID                        196
#define IDD_PROPPAGE_ELEMENT_PROPERTY   196
#define IDC_BUTTON2                     197
#define IDD_CONVER_DLG                  198
#define IDC_BUTTON4                     198
#define IDR_PNGBTN                      199
#define IDR_GIF1                        204
#define IDB_BITMAP1                     205
#define IDB_BITMAP_DOT                  205
#define IDD_DOWNLOAD_FAILURE            206
#define IDR_OPEN_LOAD_TASK              206
#define IDI_IDELETEITEM                 207
#define IDI_IDELETITEM                  207
#define IDD_DIALOG1                     208
#define IDD_SUPER_DIALOG                208
#define IDR_WC_RIBBON                   209
#define IDD_DIALOG2                     210
#define IDD_DIALOG_IEBAR                210
#define IDB_COLDTOOLBAR                 261
#define IDB_HOTTOOLBAR                  262
#define IDS_WEB_TUTORIAL                736
#define IDS_ONLINE_SUPPORT              737
#define IDS_FREE_STUFF                  738
#define IDS_GET_FASTER_INTERNET_ACCESS  741
#define IDS_FREQUENTLY_ASKED_QUESTIONS  742
#define IDS_INTERNET_START_PAGE         743
#define IDS_SEND_FEEDBACK               744
#define IDS_BEST_OF_THE_WEB             745
#define IDS_SEARCH_THE_WEB              746
#define IDS_MICROSOFT_HOME_PAGE         747
#define IDS_BACK                        748
#define IDS_FORWARD                     749
#define IDS_STOP                        750
#define IDS_REFRESH                     751
#define IDS_HOME                        752
#define IDS_SEARCH                      753
#define IDS_FAVORITES                   754
#define IDS_PRINT                       755
#define IDS_FONT                        756
#define IDS_ADDRESS                     757
#define IDC_BUTTON1                     1000
#define IDC_EXPLORE                     1000
#define IDC_BUTTON_STOP                 1001
#define IDC_BUTTON3                     1001
#define IDC_BUTTON_KILL                 1002
#define IDC_UNDO_SELECT                 1002
#define IDC_USER_NAME                   1019
#define IDC_PROGRESS1                   1023
#define IDC_TYPELIST                    1024
#define IDC_URLEDIT                     1025
#define IDC_SERVER_NAME                 1025
#define IDC_EDIT_DEEP                   1025
#define IDC_PASSWORD                    1027
#define IDC_URL_DELETE_ALL              1028
#define IDC_WAITMSG                     1028
#define IDC_CONNCTTEST                  1029
#define IDC_URL_SELECT_ALL              1029
#define IDC_LIST2                       1032
#define IDC_COMBOTRDNUMBER              1034
#define IDC_TASKCONF                    1035
#define IDC_COMBOWAITTIME               1035
#define IDC_COMBOCONNECTTRY             1036
#define IDC_TASKLIST                    1037
#define IDC_MRUNUM                      1041
#define IDC_MRUNUMEDIT                  1042
#define IDC_TASKSTART                   1060
#define IDC_TESTPROGRESS                1061
#define IDC_DOWNLOADPAGES               1063
#define IDC_DOWNLOADWEBHOST2            1064
#define IDC_DOWNLOADWEBSIT2             1065
#define IDC_INCLUDE_STRING              1066
#define IDC_HTMLTEXT                    1069
#define IDC_AUDIT_CANCEL                1069
#define IDC_CHECK_NOSCRIPT              1069
#define IDC_CHECK_SHUTDOWN              1069
#define IDC_IMAGES                      1070
#define IDC_CHECK_EDIT                  1070
#define IDC_CHECK_UNLOAD                1070
#define IDC_ZIP                         1071
#define IDC_CHECK_USEDEFAULT            1071
#define IDC_MUSIC                       1072
#define IDC_CHECK_MOUSEEVENT_LEAVE      1072
#define IDC_SWF                         1073
#define IDC_CHECK_MOUSEEVENT_MOUSEENTER 1073
#define IDC_CHECK_MOUSEEVENT_ENTER      1073
#define IDC_CHECK_SCRIPT                1074
#define IDC_PDF                         1075
#define IDC_CHECK_MOUSEEVENT_OVER       1075
#define IDC_CHM                         1076
#define IDC_CHECK_MOUSEEVENT_OUT        1076
#define IDC_CHECK_LOAD                  1077
#define IDC_CHECK_MOUSEEVENT_DOWN       1078
#define IDC_TIMEREMAIN                  1083
#define IDC_LOCATIONEDIT                1084
#define IDC_TRDNUMBER                   1085
#define IDC_MAXWAIT                     1086
#define IDC_CONNECTTRY                  1087
#define IDS_STRING1087                  1087
#define IDC_DOWNWEB2CHM                 1088
#define IDC_DOWNWEB                     1089
#define IDC_MRUTASK                     1091
#define IDC_INFDISP                     1098
#define IDC_MAX_TOTLE_SIZE              1100
#define IDC_WORK_MODE_COMBO             1100
#define IDC_MAX_FILE_SIZE               1101
#define IDC_BUTTON_START                1102
#define IDC_LIMIT                       1104
#define IDC_MAX_FILE_NUMBER             1105
#define IDC_USE_PROXY                   1107
#define IDC_SPIN_DEEP                   1108
#define IDC_STATIC_DEEP                 1109
#define IDC_URL_EXIT                    1109
#define IDC_URL_DELETE                  1110
#define IDC_CHECK_MOUSEEVENT            1111
#define IDC_CHECK_MOUSEEVENT_CLICK      1111
#define IDC_TASKSTART2                  1113
#define IDC_TASKCONF2                   1114
#define IDC_LOCATIONEDIT2               1115
#define IDC_BUTTON_ANCHOR_HELP          1116
#define IDC_STATIC_STATE                1117
#define IDC_CHECK_WARZARD               1118
#define IDC_COMBO_WORKMODE              1119
#define IDC_BUTTON_HELP                 1120
#define IDC_BUTTON_OTHER                1121
#define IDC_STATIC_S                    1122
#define IDC_STATIC_U                    1123
#define IDC_STATIC_P                    1124
#define IDC_PLACEHOLDER                 1125
#define IDC_STATIC_INFO                 1126
#define IDC_STATIC_URL                  1127
#define IDC_COMBO_URL                   1128
#define IDC_LIST_URL                    1129
#define IDC_COMBO1                      1130
#define IDC_URL_COMBO                   1130
#define IDC_WORKMODE_CAP                1131
#define IDC_LIST1                       1134
#define IDC_RAW_DATA_LIST               1134
#define IDC_STATIC_SPPORT               1135
#define IDC_STATIC_WEBSITE              1136
#define IDC_STATIC_TOTAL_SIZE           1137
#define IDC_STATIC_FILE_SIZE            1138
#define IDC_STATIC_MAX_FILES            1139
#define IDC_STATIC_MAX_FILE             1139
#define IDC_BUTTON_ADVANCE              1140
#define IDC_CHECK_ASK_BEFORE            1141
#define IDC_STATIC_SAVETO               1142
#define IDC_PLAYER                      1143
#define IDC_PATH_STRING_PART            1143
#define IDC_STATIC1                     1145
#define IDC_TAG_TYPE                    1147
#define IDC_RAW_DATA                    1148
#define IDC_RECTANGLE                   1149
#define IDC_URL_LIST                    1154
#define IDC_EDIT1                       1154
#define ID_RETRY                        1155
#define ID_ABOND                        1156
#define IDC_DEL_URLS                    1157
#define IDS_FILETYPES                   1201
#define IDB_PANEL_BAR_0                 3000
#define IDB_PANEL_BAR_1                 3001
#define IDB_PANEL_BAR_2                 3002
#define IDB_PANEL_BAR_3                 3003
#define IDB_PANEL_BAR_4                 3004
#define IDB_PANEL_BAR_5                 3005
#define ID_REGISTER                     32771
#define ID_CONFIG_SYSCONFIG             32772
#define ID_CONFIG_TASKCONFIG            32773
#define ID_VIEW_PROPERTYPANEL           32774
#define ID_FILE_MRU_FILELIST            32775
#define ID_VIEW_STOP                    32778
#define ID_VIEW_REFRESH                 32779
#define ID__STOPJOB                     32780
#define ID__ABANDONJOB                  32781
#define ID_VIEW_FONTS_LARGEST           32782
#define ID_VIEW_FONTS_LARGE             32783
#define ID__RESUMEJOB                   32783
#define ID_VIEW_FONTS_MEDIUM            32784
#define ID__PAUSEJOB                    32784
#define ID_VIEW_FONTS_SMALL             32785
#define ID_VIEW_FONTS_SMALLEST          32786
#define ID_VIEW_ANCHORPANEL             32786
#define ID_GO_BACK                      32787
#define ID_GO_FORWARD                   32788
#define ID_GO_START_PAGE                32789
#define ID_GO_SEARCH_THE_WEB            32790
#define ID_GO_BEST_OF_THE_WEB           32791
#define ID_FAVORITES_DROPDOWN           32792
#define ID_FONT_DROPDOWN                32793
#define ID_TASK_REFRESH                 32794
#define ID_HELP_WEB_TUTORIAL            32798
#define ID_HELP_CHECKFORUPDATE          32799
#define ID_TUTORIAL                     32801
#define ID_HELP_TOPICS                  32804
#define ID_OPENDIRECTORY_LOADTASK       32805
#define ID_HISTORYMENU_OPENDIRECTORY    32806
#define ID_LOADTASK                     32807
#define ID_HELP_MICROSOFT_ON_THE_WEB_BEST_OF_THE_WEB 32808
#define ID_OPENDIRECTORY                32808
#define ID_HELP_MICROSOFT_ON_THE_WEB_FREE_STUFF 32809
#define ID_Menu                         32809
#define ID_HELP_MICROSOFT_ON_THE_WEB_FREQUENTLY_ASKED_QUESTIONS 32810
#define ID_LOADMISSION                  32810
#define ID_HELP_MICROSOFT_ON_THE_WEB_GET_FASTER_INTERNET_ACCESS 32811
#define ID_SUPER_KEY                    32811
#define ID_HELP_MICROSOFT_ON_THE_WEB_INTERNET_START_PAGE 32812
#define ID_HELP_MICROSOFT_ON_THE_WEB_MICROSOFT_HOME_PAGE 32813
#define ID_BUTTON2                      32813
#define ID_HELP_MICROSOFT_ON_THE_WEB_SEARCH_THE_WEB 32814
#define ID_HELP_MICROSOFT_ON_THE_WEB_SEND_FEEDBACK 32815
#define ID_HELP_ONLINE_SUPPORT          32816
#define ID_BOGUS                        32818
#define IDS_PROMPT_CREATE_DIRECTORY1    61449
#define IDS_LOAD_JOB_COMPLETE           61450

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        211
#define _APS_NEXT_COMMAND_VALUE         32814
#define _APS_NEXT_CONTROL_VALUE         1155
#define _APS_NEXT_SYMED_VALUE           128
#endif
#endif
